[project]
name = "homelab-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.35.87",
    "mlflow>=2.19.0",
    "scikit-learn>=1.5.0",
]
